# Generated by Django 3.2.8 on 2021-10-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=50, verbose_name='Name')),
                ('description', models.CharField(default=0, max_length=200, verbose_name='Description')),
                ('category', models.CharField(default=0, max_length=50, verbose_name='Category')),
                ('brand', models.CharField(default=0, max_length=50, verbose_name='Brand')),
                ('sellPrice', models.IntegerField(default=0)),
                ('packaging', models.CharField(default=0, max_length=50, verbose_name='Packaging')),
                ('volume', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('status', models.CharField(default=0, max_length=20, verbose_name='Status')),
            ],
        ),
    ]
