# Generated by Django 3.2.8 on 2021-10-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_productinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=50, verbose_name='Name')),
                ('companyId', models.CharField(default=0, max_length=50, verbose_name='CompanyId')),
                ('address', models.CharField(default=0, max_length=50, verbose_name='Address')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('country', models.CharField(default=0, max_length=20, verbose_name='Country')),
                ('contactName', models.CharField(default=0, max_length=50, verbose_name='ConactName')),
                ('status', models.CharField(default=0, max_length=20, verbose_name='Status')),
            ],
        ),
    ]
