# Generated by Django 3.2.8 on 2021-10-27 02:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(default=0, max_length=50, verbose_name='PaymentMethod')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default=0, max_length=20, verbose_name='Status')),
                ('createdByUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrderCreatedByUserId', to=settings.AUTH_USER_MODEL)),
                ('idSupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrderIdSupplier', to='authApp.supplier')),
            ],
        ),
    ]
