# Generated by Django 3.2.8 on 2021-10-27 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('unitPrice', models.IntegerField(default=0)),
                ('taxPercentage', models.IntegerField(default=0)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPurchaseOrderIdProduct', to='authApp.product')),
                ('idPurchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productPurchaseOrderIdPurchaseOrder', to='authApp.purchaseorder')),
            ],
        ),
    ]
