# Generated by Django 3.2.8 on 2021-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_productpurchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productinvoice',
            name='taxPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productinvoice',
            name='unitPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productpurchaseorder',
            name='taxPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productpurchaseorder',
            name='unitPrice',
            field=models.FloatField(default=0),
        ),
    ]
