# Generated by Django 3.2.8 on 2021-12-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_auto_20211028_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cc',
            field=models.CharField(default=0, max_length=50, verbose_name='CC'),
        ),
    ]
